apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: xavicampa/pegarata-api
  newName: xavicampa/pegarata-api
  newTag: d011a079eabd0d68f952fb162017c9d33a8cef45
