resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: xavic-test
  newName: xavicampa/xavic-test
  newTag: 5b3c1cb436f4e4c3b2fdf280aa99ca53ac4eeef5
