resources:
- deployment.yaml
- service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: xavic-test
  newName: xavicampa/xavic-test
  newTag: cc5501d842e849a8e5ac2f310b88903f9a9596b0
