apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
images:
- name: xavicampa/xavic-test
  newName: xavicampa/xavic-test
  newTag: 15a92c1abf7b29155e990d5a8c1cb02334e36ac8
