apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namePrefix: dev-
images:
- name: xavicampa/pegarata-api
  newName: xavicampa/pegarata-api
  newTag: ba4b7cc45ae810b65a792fab09507ae84b04a52b
