apiVersion: apps/v1
kind: Deployment
metadata:
    name: pegarata-api-deployment
spec:
    selector:
        matchLabels:
            app: pegarata-api
    replicas: 2
    template:
        metadata:
            labels:
                app: pegarata-api
        spec:
            containers:
            -   name: pegarata-api-container
                image: xavicampa/pegarata-api:latest
                ports:
                - containerPort: 8080
                resources:
                    requests:
                        memory: "64Mi"
                        cpu: "250m"
                    limits:
                        memory: "128Mi"
                        cpu: "500m"
